name: Android Build and Deployment Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Setup Environment and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Generate app bundle
        run: ./gradlew app:bundleRelease --stacktrace
        
      - name: Sign app bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASS }}
          keyPassword: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.2"
          
#   STEP 2 : Upload the Artifact
  upload:
    needs: [ build ]
    name: Upload the signed artifact
    runs-on: ubuntu-latest
    steps:
      - name: Upload Bundle
        uses: actions/upload-artifact@v2
        with:
          name: signed_app_bundle
          path: app/build/outputs/bundle/release/app-release.aab
          
  
  # Step 3 : Release to playstore
  deploy:
    needs: [ build ]
    name: Create release on Playstore
    runs-on: ubuntu-latest
    steps:
      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJson: service_account.json
          packageName: ${{ github.event.inputs.app_id }}
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: internal
          whatsNewDirectory: whatsnew/
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          inAppUpdatePriority: 5
